steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/test-01/test-docker-reg-01/test-nginx:1.1.0', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/test-01/test-docker-reg-01/test-nginx']
  env:
  - 'BUILD=$BUILD_ID'