apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-nginx
  template:
    metadata:
      labels:
        app: test-nginx
    spec:
      containers:
      - name: test-nginx
        image: europe-west1-docker.pkg.dev/test-01/test-docker-reg-01/test-nginx:1.1.0
        ports:
        - containerPort: 80