apiVersion: v1
kind: Service
metadata:
  name: test-nginx-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: test-nginx
    component: users
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
